---

- name: test if postfix_myhostname is set correctly
  ansible.builtin.assert:
    that:
      - postfix_myhostname is defined
      - postfix_myhostname is string
    quiet: yes

- name: test if postfix_mydomain is set correctly
  ansible.builtin.assert:
    that:
      - postfix_mydomain is defined
      - postfix_mydomain is string
    quiet: yes

- name: test if postfix_myorigin is set correctly
  ansible.builtin.assert:
    that:
      - postfix_myorigin is defined
      - postfix_myorigin is string
    quiet: yes

- name: test if postfix_inet_interfaces is set correctly
  ansible.builtin.assert:
    that:
      - postfix_inet_interfaces is defined
      - postfix_inet_interfaces is string
    quiet: yes

- name: test if postfix_banner is set correctly
  ansible.builtin.assert:
    that:
      - postfix_banner is string
    quiet: yes
  when:
    - postfix_banner is defined

- name: test if postfix_mydestination is set correctly
  ansible.builtin.assert:
    that:
      - postfix_mydestination is defined
      - postfix_mydestination is string
    quiet: yes

- name: test if postfix_mynetworks is set correctly
  ansible.builtin.assert:
    that:
      - postfix_mynetworks is defined
      - postfix_mynetworks is string
    quiet: yes

- name: test if postfix_smtpd_recipient_restrictions is set correctly
  ansible.builtin.assert:
    that:
      - postfix_smtpd_recipient_restrictions is defined
      - postfix_smtpd_recipient_restrictions is iterable
    quiet: yes

- name: test if postfix_smtpd_sender_restrictions is set correctly
  ansible.builtin.assert:
    that:
      - postfix_smtpd_sender_restrictions is defined
      - postfix_smtpd_sender_restrictions is iterable
    quiet: yes

- name: test if postfix_smtpd_sender_restrictions is set correctly
  ansible.builtin.assert:
    that:
      - postfix_tls_protocols is string
    quiet: yes
  when:
    - postfix_tls_protocols is defined

- name: test if postfix_smtp_tls_security_level is set correctly
  ansible.builtin.assert:
    that:
      - postfix_smtp_tls_security_level is defined
      - postfix_smtp_tls_security_level is string
      - postfix_smtp_tls_security_level in [ "dane", "encrypt", "fingerprint", "may", "none", "secure", "verify" ]
    quiet: yes

- name: test if postfix_biff is set correctly
  ansible.builtin.assert:
    that:
      - postfix_biff is boolean
    quiet: yes
  when:
    - postfix_biff is defined

- name: test if postfix_append_dot_mydomain is set correctly
  ansible.builtin.assert:
    that:
      - postfix_append_dot_mydomain is boolean
    quiet: yes
  when:
    - postfix_append_dot_mydomain is defined

- name: test if postfix_alias_maps is set correctly
  ansible.builtin.assert:
    that:
      - postfix_alias_maps is string
    quiet: yes
  when:
    - postfix_alias_maps is defined

- name: test if postfix_virtual_mailbox_base is set correctly
  ansible.builtin.assert:
    that:
      - postfix_virtual_mailbox_base is string
    quiet: yes
  when:
    - postfix_virtual_mailbox_base is defined
